// Canonical migration file formats. Single source of truth shared by the migration
// runner (src/migrate.ts) and the CDK migrator's content hash
// (apps/cdk/lib/constructs/dsql-migrator). Keeping these in sync is a correctness
// invariant: if the hash covers a format the runner ignores (or vice versa), a
// migration can be silently skipped on redeploy.
//
// `.sql`  — schema changes (generated by drizzle-kit).
// `.mjs`  — batch data migrations, run identically in local (tsx/node) and Lambda (node).
//           `.ts` is intentionally NOT supported: transpiling for Lambda would make the
//           local and deployed files diverge and reintroduce double-execution hazards.
export const MIGRATION_EXTENSIONS = ['.sql', '.mjs'] as const;

export function isMigrationFile(file: string): boolean {
  return MIGRATION_EXTENSIONS.some((ext) => file.endsWith(ext));
}
