// Canonical migration file formats. Single source of truth shared by the migration
// runner (src/migrate.ts) and the CDK migrator's content hash
// (apps/cdk/lib/constructs/dsql-migrator). Keeping these in sync is a correctness
// invariant: if the hash covers a format the runner ignores (or vice versa), a
// migration can be silently skipped on redeploy.
//
// `.sql`  — schema changes (generated by drizzle-kit).
// `.mjs`  — batch data migrations, run identically in local (tsx/node) and Lambda (node).
//           `export default async function(client, context)`. The default runner does not
//           support `.ts`: it runs `migrations/` verbatim with no transpile step, so one
//           committed file must run unchanged both locally and in Lambda. If your data
//           migrations outgrow `.mjs` (large, multi-file, verification-heavy) and type-safe
//           authoring is worth the cost, ADR-005 documents the sanctioned `.ts` escape hatch.
export const MIGRATION_EXTENSIONS = ['.sql', '.mjs'] as const;

export function isMigrationFile(file: string): boolean {
  return MIGRATION_EXTENSIONS.some((ext) => file.endsWith(ext));
}
