name: Update snapshot

on:
  workflow_dispatch:
  push:
    branches:
      - 'dependabot/**'
  issue_comment:
    types: [created]

permissions:
  contents: write
jobs:
  update:
    if: >
      github.event_name == 'push' ||
      github.event_name == 'workflow_dispatch' ||
      (github.event.issue.pull_request && contains(github.event.comment.body, '/update-snapshot'))
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          ref: ${{ github.event_name == 'issue_comment' && format('refs/pull/{0}/head', github.event.issue.number) || '' }}
      - name: Use Node.js
        uses: actions/setup-node@v6
        with:
          node-version: "22.x"
      - run: |
          npm ci
          npm run test -- -u
        working-directory: ./cdk
      - name: Add & Commit
        uses: EndBug/add-and-commit@v7.2.0
        with:
          add: "cdk/test/__snapshots__/."
          message: "update snapshot"
